version: "3.9"

services:
  ex188-server:
    image: ex188-server:latest
    container_name: ex188-server
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - ex188-network-ex7

  ex188-client:
    image: ex188-client:latest
    container_name: ex188-client
    environment:
      - SERVER_PORT=8080
    networks:
      - ex188-network-ex7
    depends_on:
      - ex188-server

networks:
  ex188-network-ex7:
    external: true

